name: build and deploy repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Build Repository
        run: |
          output=$(mktemp -d)
          echo "OUTPUT=$output" >> $GITHUB_ENV
          echo "output dir: $output"
          
          # copy repo template
          cp -r ./public/* "$output/"

          cp "$output/img/AppIcon.png" "$output/CydiaIcon.png"

          rm Packages || true 2>/dev/null

          mkdir -p tmp
          for deb in debs/*.deb; do
            debname=$(sed 's/\(^debs\/\|.deb$\)//g' <<< "$deb")
            echo "---- processing $deb ($debname) ----"

            workdir="tmp/$debname"
            mkdir -p "$workdir"
            ar x "$deb" control.tar.gz --output="$workdir"

            pushd "$workdir" || exit 1
            tar -xzOf control.tar.gz > control

            if grep -qE "^Architecture: iphoneos-arm64$" control; then
              echo "detected rootless !!"
              sed -i '/^Name: /s/$/ (rootless)/' control
            fi

            if grep -qE "^Architecture: iphoneos-arm64e$" control; then
              echo "detected roothide !!"
              sed -i '/^Name: /s/$/ (roothide)/' control
            fi

            popd || exit 1

            # append to Packages
            {
              cat "$workdir/control" | grep -v "^Installed-Size"
              printf 'Filename: ./%s\n' "$deb"
              printf 'Size: %d\n' "$(stat -c %s "$deb")"
              printf 'MD5sum: %s\n' "$(md5sum "$deb" | awk '{print $1}')"
              printf 'SHA256: %s\n' "$(sha256sum "$deb" | awk '{print $1}')"
              printf '\n\n'
            } >> tmp/Packages
          done

          mv "debs" "$output/"
          bzip2 -kz tmp/Packages -c > "$output/Packages.bz2"

      - name: Build AltSource
        run: |
          output=${{ env.OUTPUT }}
          echo "output dir: $output"
          echo "Building AltSource..."
          python3 ./.github/scripts/add-altsource.py
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT }}

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
